global:
  tlsDisable: true

injector:
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.4.0"
    pullPolicy: IfNotPresent

  agentImage:
    repository: "vault"
    tag: "1.5.0"  

server:
  extraVolumes:
    - type: 'secret'
      name: 'kms-creds'

  image:
    repository: "vault"
    tag: "1.5.0"
    pullPolicy: IfNotPresent  

  ha:
    enabled: true
    replicas: 3
    
    raft:  
      enabled: true  
      config: |
        ui = true
  
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        
        seal "gcpckms" {
          project     = "us-central1"
          region      = "stellar-lock-286113"
          key_ring    = "vault"
          crypto_key  = "vault-init"
        }

        storage "raft" {
          path = "/vault/data"
        }
ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200    
